# light theme

color0 #2d3748
color1 #c53030
color2 #2d8a54
color3 #9a6318
color4 #2b6cb0
color5 #6b46c1
color6 #285e61
color7 #76808c
color8 #4a5568
color9 #c53030
color10 #2f855a
color11 #9a6318
color12 #2b6cb0
color13 #6b46c1
color14 #285e61
color15 #687078

background #c4ccd4
foreground #1a202c
cursor #1a202c
cursor_text_color #c4ccd4
selection_background #2d3748
selection_foreground #c4ccd4

active_tab_background #c4ccd4
active_tab_foreground #2b6cb0
inactive_tab_background #c4ccd4
inactive_tab_foreground #4a5568
active_border_color #2b6cb0
inactive_border_color #a0aec0
