#!/usr/bin/env bash

BACKGROUND_IMAGE="$HOME/.config/background"
WALLPAPER_DIR="$HOME/Pictures/Wallpapers"
TMP_FILE="/tmp/fzf_wallpaper_selection_$$"
KITTY_CLASS="kittymenu-switch-wallpaper"

KITTEN_ICAT='~/.local/kitty.app/bin/kitten icat \
  --clear \
  --transfer-mode=memory \
  --stdin=no \
  --place=${FZF_PREVIEW_COLUMNS}x${FZF_PREVIEW_LINES}@0x0 \
  {}'

FZF_BACKGROUND_PICKER="command ls | ~/.fzf/bin/fzf \
  --no-bold \
  --no-input \
  --layout=reverse \
  --header='Select background' \
  --color=bg+:0,fg+:12,hl+:3,border:12,gutter:-1,info:5,marker:12,pointer:1,prompt:12 \
  --preview-window='right,45%,border-left' \
  --preview='${KITTEN_ICAT}'"

select_background() {
  ~/.local/kitty.app/bin/kitty \
    --class "$KITTY_CLASS" \
    -T "$KITTY_CLASS" \
    -d "$WALLPAPER_DIR" \
    -o initial_window_width=960 \
    -o initial_window_height=230 \
    bash -c "${FZF_BACKGROUND_PICKER} > ${TMP_FILE}"
}

apply_selected_background() {
  SELECTION=$(cat "${TMP_FILE}" 2>/dev/null)
  rm -f "${TMP_FILE}"
  [[ -z $SELECTION ]] && echo "no selection." && exit 1

  if [[ -f "$BACKGROUND_IMAGE" ]] && cmp -s "${WALLPAPER_DIR}/${SELECTION}" "$BACKGROUND_IMAGE"; then
    echo "selected wallpaper is already the current background."
    exit 0
  fi

  cp "${WALLPAPER_DIR}/${SELECTION}" "$BACKGROUND_IMAGE"
  niri msg action do-screen-transition
  pkill swaybg
  swaybg -i "$BACKGROUND_IMAGE" -m fill >/dev/null 2>&1 &
}

get_current_workspace_info() {
  info=$(niri msg -j workspaces | jq -r '.[] | select(.is_focused == true and .is_active == true) | "\(.id)|\(.idx)"') || exit 1
  [[ -z "$info" ]] && exit 1
  echo "$info"
}

find_existing_window_info() {
  info=$(niri msg -j windows | jq --arg app_id "$KITTY_CLASS" -r '.[] | select(.app_id == $app_id) | "\(.id)|\(.workspace_id)"')
  [[ -z "$info" ]] && echo ""
  echo "$info"
}

handle_existing_app() {
  current_workspace_info=$(get_current_workspace_info)
  current_workspace_id=$(echo "$current_workspace_info" | cut -d "|" -f1)
  current_workspace_idx=$(echo "$current_workspace_info" | cut -d "|" -f2)
  existing_window_info=$(find_existing_window_info)
  if [[ "$existing_window_info" != "" ]]; then
    existing_window_id=$(echo "$existing_window_info" | cut -d "|" -f1)
    existing_workspace_id=$(echo "$existing_window_info" | cut -d "|" -f2)
    if [[ "$current_workspace_id" == "$existing_workspace_id" ]]; then
      exit 0
    else
      niri msg action move-window-to-workspace \
        --focus true \
        --window-id "$existing_window_id" \
        "$current_workspace_idx"

      niri msg action focus-window --id "$existing_window_id"
      exit 0
    fi
  fi
}

main() {
  handle_existing_app
  select_background
  apply_selected_background
}

main
